## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
from citipy import citipy
# Import API key
from config2 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Resources/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Marsa Matruh,EG,31.3525,27.2453,59.00,44,40,11.50,scattered clouds,2021-03-27 16:24:39
1,1,Aragarcas,BR,-15.8975,-52.2508,91.40,35,20,4.61,few clouds,2021-03-27 16:28:21
2,2,Evensk,RU,61.9500,159.2333,-7.55,87,13,9.93,few clouds,2021-03-27 16:28:21
3,3,Rikitea,PF,-23.1203,-134.9692,78.64,73,27,19.28,light rain,2021-03-27 16:28:21
4,4,Mahebourg,MU,-20.4081,57.7000,77.00,88,40,6.91,light rain,2021-03-27 16:28:22

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
#   

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
3,3,Rikitea,PF,-23.1203,-134.9692,78.64,73,27,19.28,light rain,2021-03-27 16:28:21
4,4,Mahebourg,MU,-20.4081,57.7000,77.00,88,40,6.91,light rain,2021-03-27 16:28:22
7,7,Kapaa,US,22.0752,-159.3190,73.40,78,40,14.97,scattered clouds,2021-03-27 16:28:22
12,12,Fayaoue,NC,-20.6500,166.5333,79.65,77,0,9.86,clear sky,2021-03-27 16:28:24
14,14,Kailua,US,21.4022,-157.7394,73.40,78,20,6.91,few clouds,2021-03-27 16:28:25
15,15,Saint-Philippe,RE,-21.3585,55.7679,78.80,89,75,5.75,moderate rain,2021-03-27 16:28:25
20,20,Cabedelo,BR,-6.9811,-34.8339,86.00,70,75,10.36,broken clouds,2021-03-27 16:28:26
23,23,Neuquen,AR,-38.9516,-68.0591,73.40,23,0,4.61,clear sky,2021-03-27 16:28:27
25,25,Souillac,MU,-20.5167,57.5167,77.00,88,40,6.91,scattered clouds,2021-03-27 16:28:28
26,26,Mangochi,MW,-14.4782,35.2645,72.97,88,16,4.63,light rain,2021-03-27 16:28:28

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()

preferred_cities_df.count()

preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                6
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [7]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
3,3,Rikitea,PF,-23.1203,-134.9692,78.64,73,27,19.28,light rain,2021-03-27 16:28:21
4,4,Mahebourg,MU,-20.4081,57.7000,77.00,88,40,6.91,light rain,2021-03-27 16:28:22
7,7,Kapaa,US,22.0752,-159.3190,73.40,78,40,14.97,scattered clouds,2021-03-27 16:28:22
12,12,Fayaoue,NC,-20.6500,166.5333,79.65,77,0,9.86,clear sky,2021-03-27 16:28:24
14,14,Kailua,US,21.4022,-157.7394,73.40,78,20,6.91,few clouds,2021-03-27 16:28:25
...,...,...,...,...,...,...,...,...,...,...,...
670,670,Jacareacanga,BR,-6.2222,-57.7528,83.73,74,32,3.67,scattered clouds,2021-03-27 16:31:37
672,672,Puro,PH,12.4841,123.3827,78.80,84,20,6.91,few clouds,2021-03-27 16:31:37
676,676,Neiafu,TO,-18.6500,-173.9833,78.80,89,20,10.36,few clouds,2021-03-27 16:31:39
678,678,Poum,NC,-20.2333,164.0167,80.15,75,63,10.49,broken clouds,2021-03-27 16:31:39
679,679,Thio,NC,-21.6167,166.2167,73.40,94,0,3.44,clear sky,2021-03-27 16:31:40

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.reset_index(inplace = True, drop =True)
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,78.64,light rain,-23.1203,-134.9692,
1,Mahebourg,MU,77.00,light rain,-20.4081,57.7000,
2,Kapaa,US,73.40,scattered clouds,22.0752,-159.3190,
3,Fayaoue,NC,79.65,clear sky,-20.6500,166.5333,
4,Kailua,US,73.40,few clouds,21.4022,-157.7394,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "location": "-23.1203,-134.9692"
}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotels = requests.get(base_url, params=params).json()
hotels

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -23.1206197, 'lng': -134.9687529},
    'viewport': {'northeast': {'lat': -23.1194598197085,
      'lng': -134.9673886697085},
     'southwest': {'lat': -23.1221577802915, 'lng': -134.9700866302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "Pension Maro'i",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2304,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111098332724302207930">luigia b.</a>'],
     'photo_reference': 'ATtYBwK3QB7iUrl8ZuO6c8AEg7BToMXhp7V3rfNo9fNsaUohgdqHdUhD2sVs00QzSOpRxd6vFx2_593_ioRsQq6vVYD2Xl0uKso9pPdfc_IxfPMOfyxvKrl_YDQ80B9VSK9bL7glgWbt8Py1jAXx31CA42r3MuNIKKq47HB2FS23yAGW52I_',
     'width': 4096}],
   'place_id': 'ChIJnW6Jh0aIJ54RV2HnC1r0Hjw',
   'plus_code': {'global_code': '5487V2HJ+QF'},
   'rating': 3.9,
   'reference': 'ChIJnW6Jh0aIJ54RV2HnC1r0Hjw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 16,
   'vicinity': 'Rikitea'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -23.1276524, 'lng': -134.9656596},
    'viewport': {'northeast': {'lat': -23.1263721197085,
      'lng': -134.9643507197085},
     'southwest': {'lat': -23.1290700802915, 'lng': -134.9670486802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Pension Bianca & Benoit',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115150439809622095143">Frédérick B.</a>'],
     'photo_reference': 'ATtYBwLq-6Qwk0rgHcPORflWLMpGw4iSvX6NioNdjtCTVH0JHniKsElGDE_ts5Bwe4mOJIBsBuCVxQ7QiosFgghRS2CEDJpyECgRRKuqur4t6-q3cocsGzJjXKm677Digd6qhdiUAzJzTE2k8c4At73rYrA6d_5hyGZMn4pFxlWbzu-OT50m',
     'width': 1536}],
   'place_id': 'ChIJib4T7laIJ54RcJ1rUHQ9KXk',
   'plus_code': {'global_code': '5487V2CM+WP'},
   'rating': 4.6,
   'reference': 'ChIJib4T7laIJ54RcJ1rUHQ9KXk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 13,
   'vicinity': 'BP 19 | Archipel des Gambier, Mangareva'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -23.1265385, 'lng': -134.9633665},
    'viewport': {'northeast': {'lat': -23.1251895197085,
      'lng': -134.9620175197085},
     'southwest': {'lat': -23.12788748029151, 'lng': -134.9647154802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/camping-71.png',
   'name': 'TEKOUTU RED BEACH I DREAM',
   'place_id': 'ChIJ5xY8wxKJJ54R0s3iXHTHv3Y',
   'plus_code': {'global_code': '5487V2FP+9M'},
   'reference': 'ChIJ5xY8wxKJJ54R0s3iXHTHv3Y',
   'scope': 'GOOGLE',
   'types': ['campground',
    'lodging',
    'park',
    'point_of_interest',
    'establishment'],
   'vicinity': 'French Polynesia'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -23.127968, 'lng': -134.9585572},
    'viewport': {'northeast': {'lat': -23.1266190197085,
      'lng': -134.9572082197085},
     'southwest': {'lat': -23.1293169802915, 'lng': -134.9599061802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/camping-71.png',
   'name': 'TEKOUTU RED BEACH CAMPING I DREAM',
   'place_id': 'ChIJ2-pMPVmJJ54RdAMmghvnDqc',
   'plus_code': {'global_code': '5487V2CR+RH'},
   'reference': 'ChIJ2-pMPVmJJ54RdAMmghvnDqc',
   'scope': 'GOOGLE',
   'types': ['campground',
    'lodging',
    'park',
    'point_of_interest',
    'establishment'],
   'vicinity': 'French Polynesia'}],
 'status': 'OK'}

In [10]:
len(hotels["results"])

4

In [11]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,78.64,light rain,-23.1203,-134.9692,Pension Maro'i
1,Mahebourg,MU,77.00,light rain,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
2,Kapaa,US,73.40,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
3,Fayaoue,NC,79.65,clear sky,-20.6500,166.5333,Chez Dydyce Guesthouse
4,Kailua,US,73.40,few clouds,21.4022,-157.7394,Sheffield House Bed & Breakfast
...,...,...,...,...,...,...,...
259,Jacareacanga,BR,83.73,scattered clouds,-6.2222,-57.7528,Casa do Ian😎
260,Puro,PH,78.80,few clouds,12.4841,123.3827,
261,Neiafu,TO,78.80,few clouds,-18.6500,-173.9833,Mystic Sands
262,Poum,NC,80.15,broken clouds,-20.2333,164.0167,Gîte kajeon
263,Thio,NC,73.40,clear sky,-21.6167,166.2167,La Ferme de Thio

In [13]:
hotel_df.count()

City                   264
Country                264
Max Temp               264
Current Description    264
Lat                    264
Lng                    264
Hotel Name             264
dtype: int64

In [14]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.dropna()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Rikitea,PF,78.64,light rain,-23.1203,-134.9692,Pension Maro'i
1,Mahebourg,MU,77.00,light rain,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
2,Kapaa,US,73.40,scattered clouds,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
3,Fayaoue,NC,79.65,clear sky,-20.6500,166.5333,Chez Dydyce Guesthouse
4,Kailua,US,73.40,few clouds,21.4022,-157.7394,Sheffield House Bed & Breakfast
...,...,...,...,...,...,...,...
259,Jacareacanga,BR,83.73,scattered clouds,-6.2222,-57.7528,Casa do Ian😎
260,Puro,PH,78.80,few clouds,12.4841,123.3827,
261,Neiafu,TO,78.80,few clouds,-18.6500,-173.9833,Mystic Sands
262,Poum,NC,80.15,broken clouds,-20.2333,164.0167,Gîte kajeon
263,Thio,NC,73.40,clear sky,-21.6167,166.2167,La Ferme de Thio

In [15]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:

# Add a heatmap of temperature for the vacation spots and marker for each city.
#hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"


# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [20]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_df[["Lat", "Lng"]]

In [21]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))